[95] Disable self-signup, add roles and user management system
empowerhack/DrawMyLife-Service pull request #135
Opened 2016-11-14 01:20 UTC by krissy

#### Addresses issue: #95 

***Progress: 95%***

:eyes: Reviewers: though there's one outstanding task to setup mail for all the environments, this is definitely due code review asap! Please see "What This Could Have" section below for things that are known to need improvement / fixing but will be made into post-pilot tickets. Also, there was a lot of hacky stuff we had to do to get around Devise so I'd say don't worry _too much_ about the stuff in `controllers/profiles` and `views/profiles` which hold a bunch of community-suggested overrides to get things working. 

## What this does
- [x] Remove public self-signup page
- [x] Set up roles assignment:`admin, org_admin, super_admin`. Currently, only application is super_admin ability to manage users.
- [x] Add user management section to add, edit, delete users (available to super_admins)
- [x] Configure sign-up process: super_admin creates new user details (with no password), email is sent to user to confirm email and set their own password as part of activation process (see [Screenshots](#Screenshots) below for flow)
- [x] Configure re-confirmation on email change process: similar to above
- [x] Add individual Organisation view pages linked to from user details
- [x] Create a load of custom [Devise](https://github.com/plataformatec/devise) overrides to make authentication work the way we wan it, and cater for a whole lot of edge cases and different scenarios depending on who is modifying user details and in what context (e.g. confirmation, own user profile, user management pages). 
- [ ] Update email config for staging and live environments (see [Deploy Instructions](#deploy-instructions) below for mail setup info)

## What this could have (if time permitted)

NB: These aren't blocking enough to be done before second pilot but noting here as they should be addressed eventually and be translated into tickets

- [ ] UX / Frontend love for user management system and related email layouts sent for email confirmation, password re-send, etc
- [ ] Much better test coverage
- [ ] Role assignment for org_admins as per business rules in ticket, and a sweep over the platform to see what else should have conditional access applied

## Deploy instructions

### Mail: 
NB: There is still a task to configure our staging and live mail servers as per the above checklist. Details on each of these:

On our Heroku Staging instance, we've installed the add-on [Mailtrap](https://devcenter.heroku.com/articles/mailtrap), a dummy SMTP server that will catch all our emails instead of sending them out into the real world. 

On our production instance, we've installed the add-on for the [SendGrid](https://devcenter.heroku.com/articles/sendgrid) email service.

### Deployment
- Run migrations:
  - db/migrate/20161009225419_add_role_to_users.rb
  - db/migrate/20161030193401_add_confirmable_to_devise.rb
- Push the button
- Manually update any users to super_admin in console: e.g. `your_user.role = 'super_admin; your_user.save!`

## Screenshots

### Flow:

#### User Management section (accessible by super_admin only)

<img width="1222" alt="screen shot 2016-11-14 at 00 54 33" src="https://cloud.githubusercontent.com/assets/574526/20250354/f5924b58-aa05-11e6-9df9-1dc10d51e38f.png">

#### Edit Existing User

<img width="1203" alt="screen shot 2016-11-14 at 00 54 59" src="https://cloud.githubusercontent.com/assets/574526/20250368/160ef1f6-aa06-11e6-9d44-a7e1c8571b43.png">

#### Add New User

<img width="1235" alt="screen shot 2016-11-14 at 01 01 06" src="https://cloud.githubusercontent.com/assets/574526/20250387/3718fa22-aa06-11e6-9905-48ca91c21419.png">

<img width="831" alt="screen shot 2016-11-14 at 01 01 27" src="https://cloud.githubusercontent.com/assets/574526/20250396/40355628-aa06-11e6-81bc-d43817d0e7d2.png">

#### Confirmation/Activation

<img width="877" alt="screen shot 2016-11-14 at 00 58 59" src="https://cloud.githubusercontent.com/assets/574526/20250403/50bd557c-aa06-11e6-8626-dcd6a0b5735d.png">

<img width="1222" alt="screen shot 2016-11-14 at 00 59 51" src="https://cloud.githubusercontent.com/assets/574526/20250410/696d273c-aa06-11e6-919e-e4d8f54d0cc1.png">

(User activated and auto-logged in)

<img width="1163" alt="screen shot 2016-11-14 at 01 00 09" src="https://cloud.githubusercontent.com/assets/574526/20250416/6f45ae22-aa06-11e6-9ec0-68ac27fea224.png">

2016-11-14 23:59 UTC, steverabino requested changes
- `/config/initializers/devise.rb:15` needs updating
- Should we add mailcatcher to the gemfile for development ease purposes?
- You need to add some email setup help to the README, especially as you cannot set up the app now without creating a member through console
- To make that easier, may be worth setting up a dummy first super admin through seeds file so that brand new devs will have a default user they can log in as from the start?

2016-11-14 23:59 UTC, steverabino commented on app/controllers/profiles/confirmations_controller.rb
> +    render 'profiles/confirmations/show' #Change this if you don't have the views on default path
Comment no longer required

2016-11-14 23:59 UTC, steverabino commented on app/controllers/profiles/confirmations_controller.rb
> +      render 'profiles/confirmations/new' #Change this if you don't have the views on default path
Comment no longer required

2016-11-14 23:59 UTC, steverabino commented on app/controllers/profiles/confirmations_controller.rb
> +      render 'profiles/confirmations/new' #Change this if you don't have the views on default path
Comment no longer required

2016-11-14 23:59 UTC, steverabino commented on app/controllers/profiles/sessions_controller.rb
> +  # protected
Uncomment?

2016-11-14 23:59 UTC, steverabino commented on app/views/profiles/registrations/edit.html.haml
> +                    %em (NB: only super_admins can change this)
"super_admins" should be "super admins" here

2016-11-14 23:59 UTC, stevesmith2609 commented on app/views/users/_user.html.haml
> +
Delete blank line

2016-11-14 23:59 UTC, stevesmith2609 commented on app/views/users/_users.html.haml
> +      = link_to organisation_path(user.organisation) do
user.organisation is not required; this will error if user has no organisation

2016-11-14 23:59 UTC, stevesmith2609 commented on app/views/users/_user.html.haml
> +  = link_to organisation_path(user.organisation) do
user.organisation is not required; this will error if user has no organisation

2016-11-14 23:59 UTC, stevesmith2609 commented on app/views/users/_form.html.haml
> +          = @user.active_status_toggle_link
My preference here would be = "( #{@user.active_status_toggle_link} )" to keep it on one line, but that's a preference thing.

2016-11-14 23:59 UTC, stevesmith2609 commented on app/controllers/profiles/sessions_controller.rb
> +# before_action :configure_sign_in_params, only: [:create]
Delete if not required

2016-11-14 23:59 UTC, stevesmith2609 commented on app/controllers/profiles/passwords_controller.rb
> +    super
For this and all methods in this file.

I don't understand why you have these. If Profiles::PasswordsController inherits from Devise::PasswordsController, then isn't a method with only `super` the same as having no method at all?

2016-11-14 23:59 UTC, stevesmith2609 commented on app/helpers/users_helper.rb
> +    # Example output: [ ["superadmin", "Super Admin"], ["admin", "Admin"] ]
"super_admin" and "Super admin"

2016-11-14 23:59 UTC, stevesmith2609 commented on app/controllers/profiles/sessions_controller.rb
> +    super
As before, I don't think you need these supers (unless it's just for documentation reasons?)

2016-11-14 23:59 UTC, stevesmith2609 commented on app/controllers/profiles/confirmations_controller.rb
> +          @confirmable.errors.clear #so that we wont render :new
Space after the #

2016-11-14 23:59 UTC, stevesmith2609 commented on app/controllers/profiles/confirmations_controller.rb
> +      @confirmable.only_if_unconfirmed {yield}
Does this need to be `{ yield }` ?

2016-11-15 00:01 UTC, stevesmith2609 commented on app/controllers/profiles/sessions_controller.rb
> +    super
Unless it's for documentation purposes only?

2016-11-15 00:01 UTC, stevesmith2609 commented on app/controllers/profiles/passwords_controller.rb
> +    super
Unless it's for documentation purposes only?

2016-11-15 10:03 UTC, stevesmith2609 commented
This is incredible, @krissy, thank you! 💕

2016-11-15 23:21 UTC, krissy commented on app/controllers/profiles/sessions_controller.rb
> +    super
Good catch! Just to clarify, these were generated by Devise on creating controllers at this custom route (i.e. profile) most likely for developers' convenience if they want to make custom overrides to default methods. I've removed all of the empty methods for now as we can always consult documentation if we need to customize them in future.

2016-11-16 00:01 UTC, stevesmith2609 commented on README.md
> +	$ bundle exec rake db:seed
These two could be replaced with `bundle exec rake db:setup`; http://stackoverflow.com/a/10302357/6046659

2016-11-16 00:10 UTC, krissy commented on README.md
> +	$ bundle exec rake db:seed
Yep this one was a bit of a fuzzy decision on my part- I've kept them separate as usually people will come back to the README after initial setup for database updates, so wanted to kill two birds and show commands for both seeding and running migrations.

2016-11-16 00:12 UTC, krissy commented
All tasks done and email setup updated (including Devise from address) - hopefully ok after one last sweep?

2016-11-16 00:13 UTC, steverabino approved these changes

2016-11-17 20:53 UTC, krissy commented
🌵 Rebased on master and force-pushed 🌵

2016-11-21 13:59 UTC, merged