[#149] Restrict access to drawings and organisations
empowerhack/DrawMyLife-Service pull request #153
Opened 2017-03-06 00:19 UTC by krissy

This updates the permissions around viewing, editing or deleting drawings, restricting access to Super Admins OR those within the same organisation.

It also restricts viewing, editing or deleting Organisations to Super Admins only.

_NB: At this time, all of the urgent role permissions we need for a next pilot involving a second organisation are implemented. However, the Org Admin level is still exactly the same as a normal admin, so there is still a separate ticket (TODO write up) / task left to adjust Org Admin levels to allow them to access and create users - but only in their organisation. Super Admins will need to add new users in the meantime._

#### Addresses issue: #149

## What this does
- [x] Viewing drawings index:
  - [x] Add a new scope to the Drawing model to filter drawings by org ID
  - [x] Update the Drawings controller to restrict to super admins or use the new scope
- [x] Viewing/updating/deleting a single drawing:
  - [x] Update the Drawing model with two methods checking view and edit rules, taking into account user role and organisations
  - [x] Update the drawings controller to use the new model methods above, redirect to homepage with appropriate errors if access is denied
- [x] Restrict all Organisation access to Super Admins only with authorize method

## Screenshots

### Super admin (access to all drawings and orgs):

<img width="1234" alt="screen shot 2017-03-05 at 23 45 01" src="https://cloud.githubusercontent.com/assets/574526/23592812/2378cbaa-01fe-11e7-8641-bd1dbdae2fd2.png">

<img width="1256" alt="screen shot 2017-03-06 at 00 08 19" src="https://cloud.githubusercontent.com/assets/574526/23593062/c86eb7e8-0201-11e7-9ac8-c3ab00083295.png">

### Admin or Org admin (access to all drawings within org + no access to edit orgs):

<img width="1265" alt="screen shot 2017-03-05 at 23 44 19" src="https://cloud.githubusercontent.com/assets/574526/23592813/2b096cbc-01fe-11e7-9590-e793e664d341.png">

<img width="548" alt="screen shot 2017-03-06 at 00 08 27" src="https://cloud.githubusercontent.com/assets/574526/23593066/d8f217cc-0201-11e7-8342-e49b51b584de.png">

### Attempt to view an unauthorized drawing by accessing URL directly:

<img width="1211" alt="screen shot 2017-03-05 at 23 45 49" src="https://cloud.githubusercontent.com/assets/574526/23592814/3491f128-01fe-11e7-8ae6-efab12b0f8c8.png">

### Attempt to edit/delete an unauthorized drawing by accessing URL directly:

<img width="1233" alt="screen shot 2017-03-05 at 23 46 35" src="https://cloud.githubusercontent.com/assets/574526/23592817/396f52d0-01fe-11e7-9c92-83f072c481eb.png">

### Attempt to access/edit organisations when unauthorized

<img width="1241" alt="screen shot 2017-03-06 at 00 13 15" src="https://cloud.githubusercontent.com/assets/574526/23593071/e82f9ac0-0201-11e7-847c-b0a18f839170.png">

2017-03-06 18:39 UTC, steverabino requested changes
I think I'm right in my thinking on that comment, tested it out myself and still works as a private method.

2017-03-06 18:39 UTC, stevesmith2609 commented on app/controllers/application_controller.rb
> +  def authorize_super_admin!
I think this should be a private method as per https://github.com/empowerhack/DrawMyLife-Service/pull/153/files#diff-b49f873ae722d049d381a3fed3b3b5c5L61

2017-03-09 19:24 UTC, CathMollie commented
All worked for me. As an **Admin** user, I:

- COULD NOT see other Orgs
- COULD NOT see other users outside my Org
- COULD NOT access drawing URLs I was not authorised to see (rejected after sign-in)
- COULD see drawings by Superuser plus other Admin in my Org
- COULD edit and delete drawings by Superuser plus other Admin in my Org

2017-03-09 21:12 UTC, steverabino approved these changes
Nice PR 👍 👯

2017-03-09 21:28 UTC, merged